version: '3.8'

services:
  php-web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: php-design-patterns-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - composer-cache:/root/.composer
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped

volumes:
  composer-cache:
